slogin_metadata:
    path:     /slogin/saml2/metadata
    defaults: { _controller: SLoginBundle:Default:metadata }

slogin_acs:
    path:     /slogin/saml2/acs
    defaults: { _controller: SLoginBundle:Default:acs }

slogin_slo:
    path:     /slogin/saml2/slo
    defaults: { _controller: SLoginBundle:Default:slo }
